# Generated by Django 5.0.8 on 2026-07-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активно'), ('archived', 'Архив')], default='draft', max_length=16)),
                ('resource_limit', models.PositiveIntegerField(default=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.CharField(max_length=50)),
                ('event_start', models.CharField(max_length=50)),
                ('event_end', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('labor', models.PositiveIntegerField()),
                ('workers', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('calculation_mode', models.CharField(choices=[('fixed_labor', 'Фиксированная трудоёмкость'), ('manual_duration', 'Ручная продолжительность')], default='fixed_labor', max_length=32)),
                ('planned_shift', models.PositiveIntegerField(default=0)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
