import type { ProjectScenario, WorkDefinition } from './types';

export const initialScenario: ProjectScenario = {
  id: 'repair-demo',
  title: 'Текущий ремонт условного объекта',
  description:
    'Учебный сетевой график с параллельными работами, резервами и ограничением по доступным сотрудникам.',
  resourceLimit: 5,
  works: [
    {
      id: 'w1',
      code: '1-2',
      title: 'Подготовка объекта',
      from: '1',
      to: '2',
      duration: 3,
      labor: 9,
      workers: 3,
      dependencies: [],
    },
    {
      id: 'w2',
      code: '1-3',
      title: 'Диагностика',
      from: '1',
      to: '3',
      duration: 4,
      labor: 8,
      workers: 2,
      dependencies: [],
    },
    {
      id: 'w3',
      code: '2-4',
      title: 'Демонтаж',
      from: '2',
      to: '4',
      duration: 4,
      labor: 12,
      workers: 3,
      dependencies: ['w1'],
    },
    {
      id: 'w4',
      code: '3-4',
      title: 'Проверка оборудования',
      from: '3',
      to: '4',
      duration: 2,
      labor: 4,
      workers: 2,
      dependencies: ['w2'],
    },
    {
      id: 'w5',
      code: '4-5',
      title: 'Основные работы',
      from: '4',
      to: '5',
      duration: 6,
      labor: 24,
      workers: 4,
      dependencies: ['w3', 'w4'],
    },
    {
      id: 'w6',
      code: '4-6',
      title: 'Параллельная операция',
      from: '4',
      to: '6',
      duration: 3,
      labor: 6,
      workers: 2,
      dependencies: ['w3', 'w4'],
    },
    {
      id: 'w7',
      code: '5-7',
      title: 'Финальная сборка',
      from: '5',
      to: '7',
      duration: 3,
      labor: 9,
      workers: 3,
      dependencies: ['w5'],
    },
    {
      id: 'w8',
      code: '6-7',
      title: 'Контроль качества',
      from: '6',
      to: '7',
      duration: 2,
      labor: 4,
      workers: 2,
      dependencies: ['w6', 'w7'],
    },
  ],
};

export const defaultWorkDefinitions: WorkDefinition[] = initialScenario.works.map((work) => ({
  id: work.id,
  code: work.code,
  from: work.from,
  to: work.to,
  title: work.title,
  labor: work.labor,
  workers: work.workers,
  duration: work.duration,
  plannedShift: work.plannedShift,
  calculationMode: 'fixed-labor',
}));
