# Generated by Django 5.0.8 on 2026-07-05 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('project_duration_before', models.PositiveIntegerField(default=0)),
                ('project_duration_after', models.PositiveIntegerField(default=0)),
                ('max_workers_before', models.PositiveIntegerField(default=0)),
                ('max_workers_after', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.CharField(max_length=50)),
                ('event_start', models.CharField(max_length=50)),
                ('event_end', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('labor', models.PositiveIntegerField()),
                ('workers', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('calculation_mode', models.CharField(default='fixed_labor', max_length=32)),
                ('planned_shift', models.PositiveIntegerField(default=0)),
                ('early_start', models.IntegerField(default=0)),
                ('early_finish', models.IntegerField(default=0)),
                ('late_start', models.IntegerField(default=0)),
                ('late_finish', models.IntegerField(default=0)),
                ('total_float', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('checked', 'Проверено')], default='draft', max_length=16)),
                ('project_duration', models.PositiveIntegerField(default=0)),
                ('max_workers', models.PositiveIntegerField(default=0)),
                ('average_workers', models.FloatField(default=0)),
                ('critical_works_count', models.PositiveIntegerField(default=0)),
                ('works_with_float_count', models.PositiveIntegerField(default=0)),
                ('overload_count', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='assignments.assignment')),
            ],
        ),
    ]
