# Generated by Django 5.0.8 on 2026-07-05 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsolution',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changehistory',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='solutions.studentsolution'),
        ),
        migrations.AddField(
            model_name='studentworkitem',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='solutions.studentsolution'),
        ),
        migrations.AddField(
            model_name='changehistory',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.studentworkitem'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsolution',
            unique_together={('student', 'assignment')},
        ),
    ]
